### ISSUE TITLE
Cannot find module 'ethers'

### ISSUE THREAD

**Issue by t1nky** [immutable/imx-core-sdk#79]
After updating imx-core to 0.3.0, I'm having this error:
```
error - Error: Cannot find module 'ethers'
Require stack:
- /Users/alex/Projects/imx/node_modules/@imtbl/core-sdk/dist/index.cjs.js
```
After downgrading back to 0.2.2 everything is working, 

## Steps to Reproduce
1. Fresh TypeScript project
2. yarn add @imtbl/core-sdk
3. Run generateStarkWallet + listTokens

**Comment by ckailash** [comment]
Thanks for the report! We'll review and fix this

**Comment by zatlite** [comment]
Quick workaround for now, would be to `yarn add ethers`

**Comment by t1nky** [comment]
> Quick workaround for now, would be to `yarn add ethers`

Yeah, I need to add `debug` as well
